from abc import ABC, abstractmethod
from typing import AsyncGenerator

class BaseLLMProvider(ABC):
    @abstractmethod
    async def generate(self, prompt: str, context: str | None = None) -> str:
        pass

    @abstractmethod
    async def stream(
        self, prompt: str, context: str | None = None
    ) -> AsyncGenerator[str, None]:
        """
        Yield tokens/chunks as they are generated by the model.
        """
        pass
